print("Input value from User")
Name=input("Enter Your Name is:")
print("Welcome",Name)
age=input("Enter Your age is:")
print("Your age is:",age)
Str=int(input("Enter Your integer value is:"))
print("You entered an integer type is:",type(Str),Str)
float=float(input("Enter Your float value is:"))
print("You entered a float type is:",type(float),float)