print("\tDisplay Simple Tuple value in Python.")
tup_1=(1,2,3,4,5)
print(tup_1)
print(len(tup_1))
print(type(tup_1))
print("\tDisplay Simple String value in Python.")
tup_2=("Anas","Ahmad","Hassan","Talha")
print(tup_2)
print(len(tup_2))
print(type(tup_2))
print("\tDisplay Simple float value in Python.")
tup_3=(1.5,2.5,3.5,4.5,5.5,7.5)
print(tup_3)
print(len(tup_3))
print(type(tup_3))